### ISSUE TITLE
Request for the trained model or dataset

### ISSUE THREAD

**Issue by ekaterina-scratch** [33abrar/Blood-Related-Violence-Detection#4]
I am searching for models or datasets in order to filter out gore content. I would appreciate it if you can share anything.

**Comment by 33abrar** [comment]
Dear friend,
You can find the dataset here: https://drive.google.com/drive/folders/1-6Q7jmdAqKK-FY31Q6fJacBKem9dn3_N

For more details pls read the article: https://link.springer.com/article/10.1007/s42979-024-03198-1
### And pls give star and cite this article.

**Comment by ekaterina-scratch** [comment]
Thank you very much!
